development:
  forest_env_secret: 25e352789400cd81357cc114b5d66a5b940a48f98e3562596374a9b043492804
  forest_auth_secret: dzmJvu0yb1ikUJ2AAUvPlA
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
